import type {
  Animal,
  AnimalHato,
  Conversacion,
  NotificacionItem,
  Usuario,
} from "./types";

export const USUARIO_ACTUAL_ID = "u1";

export const usuarios: Usuario[] = [
  {
    id: "u1",
    nombre: "José Martínez",
    tipo: "vendedor",
    avatarColor: "#2E7D32",
    iniciales: "JM",
    verificado: true,
    calificacion: 4.8,
    numeroVentas: 34,
    publicacionesActivas: 6,
    resenas: 21,
    plan: "premium",
    telefono: "+504 9988-7766",
    correo: "jose.martinez@example.com",
    departamento: "Olancho",
    registroSag: "SAG-OL-04521",
  },
  {
    id: "u2",
    nombre: "Finca La Esperanza",
    tipo: "empresa",
    avatarColor: "#795548",
    iniciales: "FE",
    verificado: true,
    calificacion: 4.6,
    numeroVentas: 112,
    publicacionesActivas: 18,
    resenas: 64,
    plan: "premium",
    telefono: "+504 3344-5566",
    correo: "contacto@laesperanza.hn",
    departamento: "Comayagua",
    registroSag: "SAG-CM-01187",
  },
  {
    id: "u3",
    nombre: "Dra. Karla Ponce",
    tipo: "veterinario",
    avatarColor: "#424242",
    iniciales: "KP",
    verificado: true,
    calificacion: 5,
    numeroVentas: 0,
    publicacionesActivas: 0,
    resenas: 12,
    plan: "basico",
    telefono: "+504 8877-2233",
    correo: "karla.ponce@vet.hn",
    departamento: "Francisco Morazán",
  },
  {
    id: "u4",
    nombre: "Marvin Zelaya",
    tipo: "comprador",
    avatarColor: "#66BB6A",
    iniciales: "MZ",
    verificado: false,
    calificacion: 4.2,
    numeroVentas: 0,
    publicacionesActivas: 0,
    resenas: 3,
    plan: "gratuito",
    telefono: "+504 9911-4455",
    correo: "marvin.zelaya@example.com",
    departamento: "Yoro",
  },
  {
    id: "u5",
    nombre: "Lácteos del Valle",
    tipo: "empresa",
    avatarColor: "#D4AF37",
    iniciales: "LV",
    verificado: true,
    calificacion: 4.4,
    numeroVentas: 8,
    publicacionesActivas: 3,
    resenas: 9,
    plan: "basico",
    telefono: "+504 2233-9988",
    correo: "compras@lacteosdelvalle.hn",
    departamento: "Choluteca",
  },
];

export const animales: Animal[] = [
  {
    id: "a1",
    nombre: "Lucero",
    raza: "Brahman",
    edadMeses: 28,
    pesoKg: 480,
    sexo: "hembra",
    precio: 42000,
    tipo: "doble",
    produccionLitrosDia: 12,
    departamento: "Olancho",
    municipio: "Juticalpa",
    distanciaKm: 8,
    lat: 14.6675,
    lng: -86.2205,
    vendedorId: "u1",
    destacado: true,
    registroSag: true,
    verificado: true,
    estadoSalud: "excelente",
    vacunas: ["Fiebre aftosa", "Carbón sintomático", "Brucelosis"],
    desparasitaciones: ["Ivermectina - 12/03/2026"],
    historialVeterinario: [
      { fecha: "2026-03-12", descripcion: "Desparasitación general" },
      { fecha: "2026-01-05", descripcion: "Vacunación anual" },
    ],
    padre: "Toro Campeón (Brahman)",
    madre: "Estrella (Brahman)",
    registroGenealogico: "GEN-2023-0091",
    fotos: 6,
    colorPrimario: "#EADDC8",
    colorSecundario: "#B08968",
    publicadoHace: "hace 2 días",
    vistas: 214,
  },
  {
    id: "a2",
    nombre: "Trueno",
    raza: "Angus",
    edadMeses: 18,
    pesoKg: 390,
    sexo: "macho",
    precio: 38500,
    tipo: "carne",
    departamento: "Comayagua",
    municipio: "Comayagua",
    distanciaKm: 42,
    lat: 14.4544,
    lng: -87.6376,
    vendedorId: "u2",
    destacado: true,
    registroSag: true,
    verificado: true,
    estadoSalud: "excelente",
    vacunas: ["Fiebre aftosa", "Rabia paresiante"],
    desparasitaciones: ["Albendazol - 02/02/2026"],
    historialVeterinario: [
      { fecha: "2026-02-02", descripcion: "Desparasitación" },
    ],
    padre: "Black Duke (Angus)",
    madre: "Perla Negra (Angus)",
    registroGenealogico: "GEN-2024-0233",
    fotos: 8,
    colorPrimario: "#2b2b2b",
    colorSecundario: "#4a4a4a",
    publicadoHace: "hace 5 horas",
    vistas: 96,
  },
  {
    id: "a3",
    nombre: "Manchas",
    raza: "Holstein",
    edadMeses: 34,
    pesoKg: 520,
    sexo: "hembra",
    precio: 55000,
    tipo: "leche",
    produccionLitrosDia: 22,
    departamento: "Francisco Morazán",
    municipio: "Talanga",
    distanciaKm: 61,
    lat: 14.4008,
    lng: -87.0997,
    vendedorId: "u2",
    destacado: false,
    registroSag: true,
    verificado: true,
    estadoSalud: "bueno",
    vacunas: ["Fiebre aftosa", "Brucelosis", "IBR-DVB"],
    desparasitaciones: ["Ivermectina - 20/01/2026"],
    historialVeterinario: [
      { fecha: "2026-01-20", descripcion: "Chequeo de producción" },
      { fecha: "2025-11-10", descripcion: "Parto asistido" },
    ],
    fotos: 5,
    colorPrimario: "#ffffff",
    colorSecundario: "#2b2b2b",
    publicadoHace: "hace 1 semana",
    vistas: 341,
  },
  {
    id: "a4",
    nombre: "Canela",
    raza: "Jersey",
    edadMeses: 22,
    pesoKg: 310,
    sexo: "hembra",
    precio: 29000,
    tipo: "leche",
    produccionLitrosDia: 15,
    departamento: "Yoro",
    municipio: "El Progreso",
    distanciaKm: 15,
    lat: 15.4,
    lng: -87.8,
    vendedorId: "u5",
    destacado: false,
    registroSag: false,
    verificado: true,
    estadoSalud: "bueno",
    vacunas: ["Fiebre aftosa"],
    desparasitaciones: [],
    historialVeterinario: [],
    fotos: 4,
    colorPrimario: "#C9895A",
    colorSecundario: "#6E4A2E",
    publicadoHace: "hace 3 días",
    vistas: 128,
  },
  {
    id: "a5",
    nombre: "Rayo",
    raza: "Brangus",
    edadMeses: 24,
    pesoKg: 430,
    sexo: "macho",
    precio: 41000,
    tipo: "carne",
    departamento: "Choluteca",
    municipio: "Choluteca",
    distanciaKm: 120,
    lat: 13.3,
    lng: -87.19,
    vendedorId: "u5",
    destacado: true,
    registroSag: true,
    verificado: false,
    estadoSalud: "excelente",
    vacunas: ["Fiebre aftosa", "Carbón sintomático"],
    desparasitaciones: ["Ivermectina - 15/02/2026"],
    historialVeterinario: [],
    fotos: 7,
    colorPrimario: "#3d3226",
    colorSecundario: "#111111",
    publicadoHace: "hace 4 días",
    vistas: 77,
  },
  {
    id: "a6",
    nombre: "Paloma",
    raza: "Pardo Suizo",
    edadMeses: 30,
    pesoKg: 470,
    sexo: "hembra",
    precio: 46500,
    tipo: "doble",
    produccionLitrosDia: 14,
    departamento: "Cortés",
    municipio: "San Pedro Sula",
    distanciaKm: 95,
    lat: 15.5,
    lng: -88.03,
    vendedorId: "u1",
    destacado: false,
    registroSag: true,
    verificado: true,
    estadoSalud: "regular",
    vacunas: ["Fiebre aftosa", "Brucelosis"],
    desparasitaciones: ["Albendazol - 10/03/2026"],
    historialVeterinario: [
      { fecha: "2026-03-10", descripcion: "Tratamiento por mastitis leve" },
    ],
    fotos: 3,
    colorPrimario: "#B7A78E",
    colorSecundario: "#6B5B45",
    publicadoHace: "hace 6 días",
    vistas: 53,
  },
  {
    id: "a7",
    nombre: "Campeón",
    raza: "Simmental",
    edadMeses: 40,
    pesoKg: 610,
    sexo: "macho",
    precio: 68000,
    tipo: "reproductor",
    departamento: "Olancho",
    municipio: "Catacamas",
    distanciaKm: 22,
    lat: 14.87,
    lng: -85.9,
    vendedorId: "u1",
    destacado: true,
    registroSag: true,
    verificado: true,
    estadoSalud: "excelente",
    vacunas: ["Fiebre aftosa", "Carbón sintomático", "Brucelosis"],
    desparasitaciones: ["Ivermectina - 01/03/2026"],
    historialVeterinario: [
      { fecha: "2026-03-01", descripcion: "Evaluación reproductiva" },
    ],
    padre: "Gran Toro (Simmental)",
    madre: "Reina Dorada (Simmental)",
    registroGenealogico: "GEN-2021-0045",
    fotos: 9,
    colorPrimario: "#D9B98C",
    colorSecundario: "#8C5A2B",
    publicadoHace: "hace 1 día",
    vistas: 402,
  },
  {
    id: "a8",
    nombre: "Estrellita",
    raza: "Gyr",
    edadMeses: 20,
    pesoKg: 350,
    sexo: "hembra",
    precio: 33000,
    tipo: "leche",
    produccionLitrosDia: 10,
    departamento: "Comayagua",
    municipio: "Siguatepeque",
    distanciaKm: 55,
    lat: 14.6,
    lng: -87.83,
    vendedorId: "u2",
    destacado: false,
    registroSag: false,
    verificado: true,
    estadoSalud: "bueno",
    vacunas: ["Fiebre aftosa"],
    desparasitaciones: ["Ivermectina - 28/02/2026"],
    historialVeterinario: [],
    fotos: 4,
    colorPrimario: "#c9c2b4",
    colorSecundario: "#8a7f68",
    publicadoHace: "hace 2 semanas",
    vistas: 189,
  },
];

export const conversaciones: Conversacion[] = [
  {
    id: "c1",
    contactoId: "u2",
    animalId: "a2",
    ultimoMensaje: "¿Sigue disponible el toro Trueno?",
    hora: "10:24",
    noLeidos: 2,
    mensajes: [
      {
        id: "m1",
        autorId: "u2",
        texto: "Hola, buenos días. Vi tu publicación de Trueno.",
        hora: "10:20",
      },
      {
        id: "m2",
        autorId: "u2",
        texto: "¿Sigue disponible el toro Trueno?",
        hora: "10:24",
      },
    ],
  },
  {
    id: "c2",
    contactoId: "u4",
    animalId: "a1",
    ultimoMensaje: "Perfecto, paso mañana a verla.",
    hora: "Ayer",
    noLeidos: 0,
    mensajes: [
      {
        id: "m3",
        autorId: "u1",
        texto: "Buenas tardes, la vaca Lucero está disponible.",
        hora: "Ayer 15:02",
      },
      {
        id: "m4",
        autorId: "u4",
        texto: "Perfecto, paso mañana a verla.",
        hora: "Ayer 15:10",
      },
    ],
  },
  {
    id: "c3",
    contactoId: "u3",
    ultimoMensaje: "Te confirmo la cita para el jueves.",
    hora: "Lunes",
    noLeidos: 0,
    mensajes: [
      {
        id: "m5",
        autorId: "u3",
        texto: "Te confirmo la cita para el jueves.",
        hora: "Lunes 09:15",
      },
    ],
  },
];

export const notificaciones: NotificacionItem[] = [
  {
    id: "n1",
    tipo: "mensaje",
    titulo: "Nuevo mensaje de Finca La Esperanza",
    descripcion: "¿Sigue disponible el toro Trueno?",
    hora: "hace 10 min",
    leida: false,
  },
  {
    id: "n2",
    tipo: "animal_similar",
    titulo: "Nuevo animal similar a tus búsquedas",
    descripcion: "Vaca Holstein en Comayagua a 40 km de ti",
    hora: "hace 2 horas",
    leida: false,
  },
  {
    id: "n3",
    tipo: "vacuna",
    titulo: "Vacuna próxima a vencer",
    descripcion: "Manchas necesita refuerzo de Brucelosis en 5 días",
    hora: "hace 3 horas",
    leida: false,
  },
  {
    id: "n4",
    tipo: "favorito",
    titulo: "Bajó el precio de un favorito",
    descripcion: "Rayo ahora cuesta L. 41,000",
    hora: "Ayer",
    leida: true,
  },
  {
    id: "n5",
    tipo: "renovacion",
    titulo: "Renovación de publicación",
    descripcion: "Tu publicación de Lucero vence en 3 días",
    hora: "Ayer",
    leida: true,
  },
  {
    id: "n6",
    tipo: "promocion",
    titulo: "Mejora a Premium con 20% de descuento",
    descripcion: "Oferta válida hasta fin de mes",
    hora: "hace 2 días",
    leida: true,
  },
];

export const hato: AnimalHato[] = [
  {
    id: "h1",
    nombre: "Lucero",
    raza: "Brahman",
    edadMeses: 28,
    produccionLitrosDia: 12,
    estado: "sana",
    proximaRevision: "2026-07-10",
    ultimaVacuna: "2026-01-05",
    valorEstimado: 42000,
  },
  {
    id: "h2",
    nombre: "Campeón",
    raza: "Simmental",
    edadMeses: 40,
    estado: "sana",
    proximaRevision: "2026-07-15",
    ultimaVacuna: "2026-03-01",
    valorEstimado: 68000,
  },
  {
    id: "h3",
    nombre: "Paloma",
    raza: "Pardo Suizo",
    edadMeses: 30,
    produccionLitrosDia: 14,
    estado: "en_tratamiento",
    proximaRevision: "2026-07-03",
    ultimaVacuna: "2026-03-10",
    valorEstimado: 46500,
  },
  {
    id: "h4",
    nombre: "Dulce",
    raza: "Holstein",
    edadMeses: 26,
    produccionLitrosDia: 18,
    estado: "prenada",
    proximaRevision: "2026-08-01",
    ultimaVacuna: "2025-12-20",
    valorEstimado: 58000,
  },
  {
    id: "h5",
    nombre: "Reina",
    raza: "Jersey",
    edadMeses: 33,
    produccionLitrosDia: 0,
    estado: "seca",
    proximaRevision: "2026-07-20",
    ultimaVacuna: "2026-02-14",
    valorEstimado: 27000,
  },
];

export function getUsuario(id: string): Usuario | undefined {
  return usuarios.find((u) => u.id === id);
}

export function getAnimal(id: string): Animal | undefined {
  return animales.find((a) => a.id === id);
}
